name: Java CI

on:
  push:
    branches:
      - feature/**

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25

      - name: Run tests
        run: |
          cd tictactoe
          mvn test